name: Rust

on:
  push:
    branches: [ "canon" ]
  pull_request:
    branches: [ "canon" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Build All
      run: cargo build --verbose
    - name: Run all tests
      run: cargo test --verbose
